### ISSUE TITLE
World to screen coordinates

### ISSUE THREAD

**Issue by arusyakhov** [ARM-software/opengl-es-sdk-for-android#9]
Hi. This is not a bug, but a question. Any answer or help will be much appreciated.

I am working on an android project of augmented face using ArCore and OpenGL ES.
I need to get screen coordinates having world (x,y,z) coordinates.
I do it in the following way

       val viewMatrix = FloatArray(16)
       camera.getViewMatrix(viewMatrix, 0)

      val projectionMatrix = FloatArray(16)
      camera.getProjectionMatrix(projectionMatrix, 0, 0.1f, 100.0f)

        val view = IntArray(4)
        view[0] = 0
        view[1] = 0
        view[2] = getDisplayWidth()
        view[3] = getDisplayHeight()
        val pos = FloatArray(4)
        GLU.gluProject(coord.x, coord.y, coord.z, viewMatrix, 0, projectionMatrix, 0, view, 0 , pos, 0)

However the results are inaccurate.

**Comment by abbaswasim** [comment]
This is not related to the SDK. You should look up something like GLM world to screen space. Quick googling returns a few results including [this](https://stackoverflow.com/questions/35261192/how-to-use-glmproject-to-get-the-coordinates-of-a-point-in-world-space)

**Comment by arusyakhov** [comment]
Even long googling doesn't return anything answering my question (and the link provided by you as well). And the question is very well related to OpenGL ES Android SDK
